---
name: Package Linux

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - uses: actions/checkout@v2

      - shell: bash
        run: ls -lhR
